apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T07:29:55Z"
    crossplane.io/external-create-succeeded: "2024-07-04T07:29:56Z"
    crossplane.io/external-name: k8s-w27-s036-wh79q
  creationTimestamp: "2024-07-04T07:29:55Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s036-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s036
  name: k8s-w27-s036-wh79q
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s036
    uid: 81bd3147-a3fe-49e4-aa6f-ec7c0a0f25fc
  resourceVersion: "822856786"
  uid: cbc8d349-e62f-4c22-9771-05e55c3a0fd4
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: csi.tanzu.vmware.com/v1alpha1
      kind: VSphereCSIConfig
      metadata:
        name: k8s-w27-s036
        namespace: default
      spec:
        vsphereCSI:
          config:
            datacenter: /Demo-Datacenter
            httpProxy: ""
            httpsProxy: ""
            insecureFlag: true
            noProxy: ""
            tlsThumbprint: ""
            useTopologyCategories: false
          mode: vsphereCSI
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: csi.tanzu.vmware.com/v1alpha1
      kind: VSphereCSIConfig
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"csi.tanzu.vmware.com/v1alpha1","kind":"VSphereCSIConfig","metadata":{"name":"k8s-w27-s036","namespace":"default"},"spec":{"vsphereCSI":{"config":{"datacenter":"/Demo-Datacenter","httpProxy":"","httpsProxy":"","insecureFlag":true,"noProxy":"","tlsThumbprint":"","useTopologyCategories":false},"mode":"vsphereCSI"}}}'
        creationTimestamp: "2024-07-04T07:29:55Z"
        generation: 1
        labels:
          tkg.tanzu.vmware.com/cluster-name: k8s-w27-s036
          tkg.tanzu.vmware.com/package-name: vsphere-csi.tanzu.vmware.com.3.0.1---vmware.2-tkg.1
        managedFields:
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:spec:
              .: {}
              f:vsphereCSI:
                .: {}
                f:config:
                  .: {}
                  f:datacenter: {}
                  f:httpProxy: {}
                  f:httpsProxy: {}
                  f:insecureFlag: {}
                  f:noProxy: {}
                  f:tlsThumbprint: {}
                  f:useTopologyCategories: {}
                f:mode: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T07:29:55Z"
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:labels:
                .: {}
                f:tkg.tanzu.vmware.com/cluster-name: {}
                f:tkg.tanzu.vmware.com/package-name: {}
              f:ownerReferences:
                .: {}
                k:{"uid":"a96d47dc-5633-4886-ad06-d3137a674dda"}: {}
                k:{"uid":"d59611c5-ebd2-4426-824d-43c2250d7701"}: {}
          manager: manager
          operation: Update
          time: "2024-07-04T07:30:15Z"
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:status:
              .: {}
              f:secretRef: {}
          manager: manager
          operation: Update
          subresource: status
          time: "2024-07-04T07:30:16Z"
        name: k8s-w27-s036
        namespace: default
        ownerReferences:
        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          name: k8s-w27-s036
          uid: a96d47dc-5633-4886-ad06-d3137a674dda
        - apiVersion: run.tanzu.vmware.com/v1alpha3
          blockOwnerDeletion: true
          controller: true
          kind: ClusterBootstrap
          name: k8s-w27-s036
          uid: d59611c5-ebd2-4426-824d-43c2250d7701
        resourceVersion: "271045415"
        uid: d4f9e2fc-a464-4384-a086-fbe224d69228
      spec:
        vsphereCSI:
          config:
            datacenter: /Demo-Datacenter
            httpProxy: ""
            httpsProxy: ""
            insecureFlag: true
            noProxy: ""
            tlsThumbprint: ""
            useTopologyCategories: false
          mode: vsphereCSI
      status:
        secretRef: k8s-w27-s036-vsphere-csi-data-values
  conditions:
  - lastTransitionTime: "2024-07-04T07:29:57Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:42Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
