apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-08T07:56:19Z"
    crossplane.io/external-create-succeeded: "2024-07-08T07:56:19Z"
    crossplane.io/external-name: cna-w12-s007-2dnrf
  creationTimestamp: "2024-07-08T07:56:19Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: cna-w12-s007-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: cna-w12-s007
  name: cna-w12-s007-2dnrf
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: cna-w12-s007
    uid: 808392d7-2425-4307-820d-ddeaa1bea09d
  resourceVersion: "822857080"
  uid: d2ab0dcf-8d12-44f1-bb60-6c7ebad951f6
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cna-w12-s007
        namespace: default
      stringData:
        password: Pajama1994
        username: scott@terasky.demo
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: v1
      data:
        password: UGFqYW1hMTk5NA==
        username: c2NvdHRAdGVyYXNreS5kZW1v
      kind: Secret
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Secret","metadata":{"name":"cna-w12-s007","namespace":"default"},"stringData":{"password":"Pajama1994","username":"scott@terasky.demo"}}'
        creationTimestamp: "2024-07-08T07:56:19Z"
        finalizers:
        - vspherecluster/infrastructure.cluster.x-k8s.io
        managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:data:
              .: {}
              f:password: {}
              f:username: {}
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:type: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-08T07:56:19Z"
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:finalizers:
                .: {}
                v:"vspherecluster/infrastructure.cluster.x-k8s.io": {}
              f:ownerReferences:
                .: {}
                k:{"uid":"a8de0460-8359-4340-b439-a6dfd1bd8139"}: {}
          manager: manager
          operation: Update
          time: "2024-07-08T08:00:41Z"
        name: cna-w12-s007
        namespace: default
        ownerReferences:
        - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: VSphereCluster
          name: cna-w12-s007-7bhg5
          uid: a8de0460-8359-4340-b439-a6dfd1bd8139
        resourceVersion: "273861653"
        uid: 3b387ed5-e394-4834-8a09-5b0b0d1275a5
      type: Opaque
  conditions:
  - lastTransitionTime: "2024-07-08T07:56:19Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:51Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
