apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T07:29:55Z"
    crossplane.io/external-create-succeeded: "2024-07-04T07:29:55Z"
    crossplane.io/external-name: k8s-w27-s039-q8wvc
  creationTimestamp: "2024-07-04T07:29:55Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s039-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s039
  name: k8s-w27-s039-q8wvc
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s039
    uid: 9d288a03-29a4-49f5-80c1-469312ea9431
  resourceVersion: "822856663"
  uid: 4af6b0bb-305b-4584-a431-82c8b2ff888b
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: k8s-w27-s039-cluster-autoscaler
        name: k8s-w27-s039-cluster-autoscaler
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: k8s-w27-s039-cluster-autoscaler
        template:
          metadata:
            labels:
              app: k8s-w27-s039-cluster-autoscaler
          spec:
            containers:
            - args:
              - --cloud-provider=clusterapi
              - --v=4
              - --clusterapi-cloud-config-authoritative
              - --kubeconfig=/mnt/k8s-w27-s039-kubeconfig/value
              - --node-group-auto-discovery=clusterapi:clusterName=k8s-w27-s039,namespace=default
              - --scale-down-delay-after-add=10m
              - --scale-down-delay-after-delete=10s
              - --scale-down-delay-after-failure=3m
              - --scale-down-unneeded-time=10m
              - --max-node-provision-time=15m
              - --max-nodes-total=0
              command:
              - /cluster-autoscaler
              image: projects.registry.vmware.com/tkg/cluster-autoscaler:v1.26.2_vmware.1
              name: k8s-w27-s039-cluster-autoscaler
              volumeMounts:
              - mountPath: /mnt/k8s-w27-s039-kubeconfig
                name: k8s-w27-s039-cluster-autoscaler-volume
                readOnly: true
            serviceAccountName: k8s-w27-s039-autoscaler
            terminationGracePeriodSeconds: 10
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
            volumes:
            - name: k8s-w27-s039-cluster-autoscaler-volume
              secret:
                secretName: k8s-w27-s039-kubeconfig
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          deployment.kubernetes.io/revision: "1"
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"k8s-w27-s039-cluster-autoscaler"},"name":"k8s-w27-s039-cluster-autoscaler","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"k8s-w27-s039-cluster-autoscaler"}},"template":{"metadata":{"labels":{"app":"k8s-w27-s039-cluster-autoscaler"}},"spec":{"containers":[{"args":["--cloud-provider=clusterapi","--v=4","--clusterapi-cloud-config-authoritative","--kubeconfig=/mnt/k8s-w27-s039-kubeconfig/value","--node-group-auto-discovery=clusterapi:clusterName=k8s-w27-s039,namespace=default","--scale-down-delay-after-add=10m","--scale-down-delay-after-delete=10s","--scale-down-delay-after-failure=3m","--scale-down-unneeded-time=10m","--max-node-provision-time=15m","--max-nodes-total=0"],"command":["/cluster-autoscaler"],"image":"projects.registry.vmware.com/tkg/cluster-autoscaler:v1.26.2_vmware.1","name":"k8s-w27-s039-cluster-autoscaler","volumeMounts":[{"mountPath":"/mnt/k8s-w27-s039-kubeconfig","name":"k8s-w27-s039-cluster-autoscaler-volume","readOnly":true}]}],"serviceAccountName":"k8s-w27-s039-autoscaler","terminationGracePeriodSeconds":10,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"},{"effect":"NoSchedule","key":"node-role.kubernetes.io/control-plane"}],"volumes":[{"name":"k8s-w27-s039-cluster-autoscaler-volume","secret":{"secretName":"k8s-w27-s039-kubeconfig"}}]}}}}'
        creationTimestamp: "2024-07-04T07:29:55Z"
        generation: 1
        labels:
          app: k8s-w27-s039-cluster-autoscaler
        managedFields:
        - apiVersion: apps/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:progressDeadlineSeconds: {}
              f:replicas: {}
              f:revisionHistoryLimit: {}
              f:selector: {}
              f:strategy:
                f:rollingUpdate:
                  .: {}
                  f:maxSurge: {}
                  f:maxUnavailable: {}
                f:type: {}
              f:template:
                f:metadata:
                  f:labels:
                    .: {}
                    f:app: {}
                f:spec:
                  f:containers:
                    k:{"name":"k8s-w27-s039-cluster-autoscaler"}:
                      .: {}
                      f:args: {}
                      f:command: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                      f:volumeMounts:
                        .: {}
                        k:{"mountPath":"/mnt/k8s-w27-s039-kubeconfig"}:
                          .: {}
                          f:mountPath: {}
                          f:name: {}
                          f:readOnly: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:serviceAccount: {}
                  f:serviceAccountName: {}
                  f:terminationGracePeriodSeconds: {}
                  f:tolerations: {}
                  f:volumes:
                    .: {}
                    k:{"name":"k8s-w27-s039-cluster-autoscaler-volume"}:
                      .: {}
                      f:name: {}
                      f:secret:
                        .: {}
                        f:defaultMode: {}
                        f:secretName: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T07:29:55Z"
        - apiVersion: apps/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                f:deployment.kubernetes.io/revision: {}
            f:status:
              f:availableReplicas: {}
              f:conditions:
                .: {}
                k:{"type":"Available"}:
                  .: {}
                  f:lastTransitionTime: {}
                  f:lastUpdateTime: {}
                  f:message: {}
                  f:reason: {}
                  f:status: {}
                  f:type: {}
                k:{"type":"Progressing"}:
                  .: {}
                  f:lastTransitionTime: {}
                  f:lastUpdateTime: {}
                  f:message: {}
                  f:reason: {}
                  f:status: {}
                  f:type: {}
              f:observedGeneration: {}
              f:readyReplicas: {}
              f:replicas: {}
              f:updatedReplicas: {}
          manager: kube-controller-manager
          operation: Update
          subresource: status
          time: "2024-07-04T07:32:05Z"
        name: k8s-w27-s039-cluster-autoscaler
        namespace: default
        resourceVersion: "271047794"
        uid: 737cd9aa-eaed-411f-ad64-e245ca2f08a3
      spec:
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: k8s-w27-s039-cluster-autoscaler
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: k8s-w27-s039-cluster-autoscaler
          spec:
            containers:
            - args:
              - --cloud-provider=clusterapi
              - --v=4
              - --clusterapi-cloud-config-authoritative
              - --kubeconfig=/mnt/k8s-w27-s039-kubeconfig/value
              - --node-group-auto-discovery=clusterapi:clusterName=k8s-w27-s039,namespace=default
              - --scale-down-delay-after-add=10m
              - --scale-down-delay-after-delete=10s
              - --scale-down-delay-after-failure=3m
              - --scale-down-unneeded-time=10m
              - --max-node-provision-time=15m
              - --max-nodes-total=0
              command:
              - /cluster-autoscaler
              image: projects.registry.vmware.com/tkg/cluster-autoscaler:v1.26.2_vmware.1
              imagePullPolicy: IfNotPresent
              name: k8s-w27-s039-cluster-autoscaler
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /mnt/k8s-w27-s039-kubeconfig
                name: k8s-w27-s039-cluster-autoscaler-volume
                readOnly: true
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: k8s-w27-s039-autoscaler
            serviceAccountName: k8s-w27-s039-autoscaler
            terminationGracePeriodSeconds: 10
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
            volumes:
            - name: k8s-w27-s039-cluster-autoscaler-volume
              secret:
                defaultMode: 420
                secretName: k8s-w27-s039-kubeconfig
      status:
        availableReplicas: 1
        conditions:
        - lastTransitionTime: "2024-07-04T07:32:05Z"
          lastUpdateTime: "2024-07-04T07:32:05Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
        - lastTransitionTime: "2024-07-04T07:29:55Z"
          lastUpdateTime: "2024-07-04T07:32:05Z"
          message: ReplicaSet "k8s-w27-s039-cluster-autoscaler-7476d9ccdd" has successfully
            progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
        observedGeneration: 1
        readyReplicas: 1
        replicas: 1
        updatedReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-04T07:29:57Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:39Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
