apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T07:29:55Z"
    crossplane.io/external-create-succeeded: "2024-07-04T07:29:55Z"
    crossplane.io/external-name: k8s-w27-s038-chbgm
  creationTimestamp: "2024-07-04T07:29:55Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s038-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s038
  name: k8s-w27-s038-chbgm
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s038
    uid: 007f1f22-6169-4c34-9cd4-de6c680fa2fe
  resourceVersion: "822856565"
  uid: 26281a3d-ffb4-4e87-bf65-7c353dbdc2e1
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: k8s-w27-s038-autoscaler-management
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-autoscaler-management
      subjects:
      - kind: ServiceAccount
        name: k8s-w27-s038-autoscaler
        namespace: default
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"name":"k8s-w27-s038-autoscaler-management"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-autoscaler-management"},"subjects":[{"kind":"ServiceAccount","name":"k8s-w27-s038-autoscaler","namespace":"default"}]}'
        creationTimestamp: "2024-07-04T07:29:55Z"
        managedFields:
        - apiVersion: rbac.authorization.k8s.io/v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:roleRef: {}
            f:subjects: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T07:29:55Z"
        name: k8s-w27-s038-autoscaler-management
        resourceVersion: "271044852"
        uid: 6f4b79c7-68f6-464f-afe3-0fae6907fdb2
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-autoscaler-management
      subjects:
      - kind: ServiceAccount
        name: k8s-w27-s038-autoscaler
        namespace: default
  conditions:
  - lastTransitionTime: "2024-07-04T07:29:55Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:36Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
