apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T06:55:48Z"
    crossplane.io/external-create-succeeded: "2024-07-04T06:55:48Z"
    crossplane.io/external-name: k8s-w27-s030-gjjbk
  creationTimestamp: "2024-07-04T06:55:40Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s030-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s030
  name: k8s-w27-s030-gjjbk
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s030
    uid: 813a7414-30e8-46eb-b8e8-163a545ba950
  resourceVersion: "822856605"
  uid: e8d60cd2-0ded-46dc-a1d2-bd5939effd0a
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: k8s-w27-s030-autoscaler
        namespace: default
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"name":"k8s-w27-s030-autoscaler","namespace":"default"}}'
        creationTimestamp: "2024-07-04T06:55:48Z"
        managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T06:55:48Z"
        name: k8s-w27-s030-autoscaler
        namespace: default
        resourceVersion: "271015808"
        uid: 771196a0-a5f5-4b6d-b73f-14812a792093
  conditions:
  - lastTransitionTime: "2024-07-04T06:55:48Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:37Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
