apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T07:29:55Z"
    crossplane.io/external-create-succeeded: "2024-07-04T07:29:55Z"
    crossplane.io/external-name: k8s-w27-s037-wktwc
  creationTimestamp: "2024-07-04T07:29:55Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s037-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s037
  name: k8s-w27-s037-wktwc
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s037
    uid: 76a08609-c2df-491f-bb4f-38ed19560d8d
  resourceVersion: "822856626"
  uid: 7569ca91-cd8c-46f7-923b-adbc8c858423
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: k8s-w27-s037-autoscaler
        namespace: default
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"name":"k8s-w27-s037-autoscaler","namespace":"default"}}'
        creationTimestamp: "2024-07-04T07:29:55Z"
        managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T07:29:55Z"
        name: k8s-w27-s037-autoscaler
        namespace: default
        resourceVersion: "271044875"
        uid: b645a686-5a8d-4fad-8cc7-8c3c96c8062f
  conditions:
  - lastTransitionTime: "2024-07-04T07:29:55Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:38Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
