apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/external-create-pending: "2024-07-04T06:55:55Z"
    crossplane.io/external-create-succeeded: "2024-07-04T06:55:55Z"
    crossplane.io/external-name: k8s-w27-s030-mddd2
  creationTimestamp: "2024-07-04T06:55:41Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: k8s-w27-s030-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: k8s-w27-s030
  name: k8s-w27-s030-mddd2
  ownerReferences:
  - apiVersion: tkg.terasky.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: LabCluster
    name: k8s-w27-s030
    uid: 813a7414-30e8-46eb-b8e8-163a545ba950
  resourceVersion: "822856685"
  uid: dfca5a0e-881b-4cad-8bc5-470479bad5c8
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: csi.tanzu.vmware.com/v1alpha1
      kind: VSphereCSIConfig
      metadata:
        name: k8s-w27-s030
        namespace: default
      spec:
        vsphereCSI:
          config:
            datacenter: /Demo-Datacenter
            httpProxy: ""
            httpsProxy: ""
            insecureFlag: true
            noProxy: ""
            tlsThumbprint: ""
            useTopologyCategories: false
          mode: vsphereCSI
  managementPolicy: Default
  providerConfigRef:
    name: mgmt-cluster
  readiness:
    policy: SuccessfulCreate
status:
  atProvider:
    manifest:
      apiVersion: csi.tanzu.vmware.com/v1alpha1
      kind: VSphereCSIConfig
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"csi.tanzu.vmware.com/v1alpha1","kind":"VSphereCSIConfig","metadata":{"name":"k8s-w27-s030","namespace":"default"},"spec":{"vsphereCSI":{"config":{"datacenter":"/Demo-Datacenter","httpProxy":"","httpsProxy":"","insecureFlag":true,"noProxy":"","tlsThumbprint":"","useTopologyCategories":false},"mode":"vsphereCSI"}}}'
        creationTimestamp: "2024-07-04T06:55:55Z"
        generation: 1
        labels:
          tkg.tanzu.vmware.com/cluster-name: k8s-w27-s030
          tkg.tanzu.vmware.com/package-name: vsphere-csi.tanzu.vmware.com.3.0.1---vmware.2-tkg.1
        managedFields:
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:spec:
              .: {}
              f:vsphereCSI:
                .: {}
                f:config:
                  .: {}
                  f:datacenter: {}
                  f:httpProxy: {}
                  f:httpsProxy: {}
                  f:insecureFlag: {}
                  f:noProxy: {}
                  f:tlsThumbprint: {}
                  f:useTopologyCategories: {}
                f:mode: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-07-04T06:55:55Z"
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:labels:
                .: {}
                f:tkg.tanzu.vmware.com/cluster-name: {}
                f:tkg.tanzu.vmware.com/package-name: {}
              f:ownerReferences:
                .: {}
                k:{"uid":"4c17a236-33f3-41b6-a73b-68c9227ce800"}: {}
                k:{"uid":"5d38b867-b1d6-4a45-b129-be0ff7d63456"}: {}
          manager: manager
          operation: Update
          time: "2024-07-04T06:57:05Z"
        - apiVersion: csi.tanzu.vmware.com/v1alpha1
          fieldsType: FieldsV1
          fieldsV1:
            f:status:
              .: {}
              f:secretRef: {}
          manager: manager
          operation: Update
          subresource: status
          time: "2024-07-04T06:59:40Z"
        name: k8s-w27-s030
        namespace: default
        ownerReferences:
        - apiVersion: cluster.x-k8s.io/v1beta1
          kind: Cluster
          name: k8s-w27-s030
          uid: 5d38b867-b1d6-4a45-b129-be0ff7d63456
        - apiVersion: run.tanzu.vmware.com/v1alpha3
          blockOwnerDeletion: true
          controller: true
          kind: ClusterBootstrap
          name: k8s-w27-s030
          uid: 4c17a236-33f3-41b6-a73b-68c9227ce800
        resourceVersion: "271019272"
        uid: 269c7dea-a2b7-4212-be17-0cc771a2718a
      spec:
        vsphereCSI:
          config:
            datacenter: /Demo-Datacenter
            httpProxy: ""
            httpsProxy: ""
            insecureFlag: true
            noProxy: ""
            tlsThumbprint: ""
            useTopologyCategories: false
          mode: vsphereCSI
      status:
        secretRef: k8s-w27-s030-vsphere-csi-data-values
  conditions:
  - lastTransitionTime: "2024-07-04T06:55:55Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-11-03T09:44:39Z"
    message: 'connect failed: cannot create new Kubernetes client: cannot create Kubernetes
      client: the server has asked for the client to provide credentials'
    reason: ReconcileError
    status: "False"
    type: Synced
